[tool.poetry]
name = "flaskproject"
version = "0.1.0"
description = ""
authors = ["Aliya Kalimullina <pu_49@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
flask = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
